### ISSUE TITLE
VersionUnavailable error with standalone exe on Windows 7

### ISSUE THREAD

**Issue by Zzooouhh** [Pyrdacor/Ambermoon.net#182]
I'm trying to run the standalone version (v1.0.0) on Win 7 64-bit, but launching Ambermoon.net.exe merely throws this error:
```
VersionUnavailable: WGL: OpenGL profile requested but WGL_ARB_create_context_pro
file is unavailable
   at Silk.NET.GLFW.Glfw.<>c.<.cctor>b__141_0(ErrorCode errorCode, String descri
ption)
   at Silk.NET.GLFW.Glfw.CreateWindow(Int32 width, Int32 height, String title, M
onitor* monitor, WindowHandle* share)
   at Silk.NET.Windowing.Glfw.GlfwWindow.CoreInitialize(WindowOptions opts)
   at Silk.NET.Windowing.Internals.WindowImplementationBase.CoreInitialize(ViewO
ptions opts)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
```

**Comment by Pyrdacor** [comment]
Do you know what OpenGL you use? Ambermoon.net needs at least OpenGL 3.1 to work. Maybe your graphics hardware is too old? But OpenGL 3.1 is from March 2009 so I guess it is unlikely.

**Comment by Pyrdacor** [comment]
Maybe a driver update can help. This error is often caused by old hardware or driver. For example integrated Intel graphic cards etc.

**Comment by Zzooouhh** [comment]
Version according to wglinfo is `[WGL] OpenGL version string: 3.1.0 - Build 9.17.10.3347` so it should be barely within the limits then. But I can try an update whether makes a difference.

**Comment by Pyrdacor** [comment]
Couldn't hurt to use an updated driver. As I said OpenGL 3.1 is very old (more than 12 years now).

**Comment by a1exh** [comment]
Probably not. You could try downloading glfw DLLs and putting them in the same directory as Ambermoon. That might bypass the built in glfw. But you will probably get the same error msg

https://www.glfw.org/download

**Comment by Zzooouhh** [comment]
Thanks for going through the trouble to dig up the info. I guess it'll probably be simpler for me to just play the original in WinUAE for the time being then :) But it's still odd that OpenGL 3.1 doesn't run anyway.

**Comment by Pyrdacor** [comment]
Sorry that it does not work. I might have a solution that I can provide in the code. I will try tomorrow and provide a updated Exe for you to test.

**Comment by Pyrdacor** [comment]
Can you please test with this version? https://github.com/Pyrdacor/Ambermoon.net/raw/master/Tests/Ambermoon.net.zip

**Comment by Pyrdacor** [comment]
@Zzooouhh Let me know if it worked out when you got time for it. ;)

**Comment by Zzooouhh** [comment]
@Pyrdacor Sorry for late response. No, this version throws the same error.

**Comment by Pyrdacor** [comment]
Thanks. One more test please. Download the same file again please and test.

**Comment by Zzooouhh** [comment]
Still doesn't run, but this time the error message is different:
```
InvalidValue: Context profiles are only defined for OpenGL version 3.2 and above

   at Silk.NET.GLFW.Glfw.<>c.<.cctor>b__141_0(ErrorCode errorCode, String descri
ption)
   at Silk.NET.GLFW.Glfw.CreateWindow(Int32 width, Int32 height, String title, M
onitor* monitor, WindowHandle* share)
   at Silk.NET.Windowing.Glfw.GlfwWindow.CoreInitialize(WindowOptions opts)
   at Silk.NET.Windowing.Internals.WindowImplementationBase.CoreInitialize(ViewO
ptions opts)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
```

**Comment by Pyrdacor** [comment]
I fear I can't help you then. :(
