### ISSUE TITLE
Issue with Ambermoon.net.exe when using cmd with output command

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#211]
hi,

issue was reported by invisiblehsadow at discord.
i can confirm it.
game is starting very well, but its not possible to change options and leave the menu.

`***** Ambermoon Cheat Console *****
Type 'help' for more information.

Das Handle ist ungltig.
   at System.ConsolePal.Clear()
   at Ambermoon.GameWindow.<>c__DisplayClass65_0.<StartGame>b__11(IConfiguration configuration, Boolean windowChange)
   at Ambermoon.Game.NotifyConfigurationChange(Boolean windowChange)
   at Ambermoon.UI.Layout.<>c__DisplayClass118_0.<OpenOptions>b__24()
   at Ambermoon.UI.Button.ExecuteActions(UInt32 currentTicks, Boolean rightMouse)
   at Ambermoon.UI.Button.LeftMouseUp(Position position, Nullable`1& cursorType, UInt32 currentTicks)
   at Ambermoon.UI.Popup.LeftMouseUp(Position position)
   at Ambermoon.UI.Layout.LeftMouseUp(Position position, Nullable`1& newCursorType, UInt32 currentTicks)
   at Ambermoon.Game.OnMouseUp(Position cursorPosition, MouseButtons buttons)
   at Ambermoon.GameWindow.Mouse_MouseUp(IMouse mouse, MouseButton button)
   at Silk.NET.Input.Internals.MouseImplementationBase.HandleMouseUp(IMouse mouse, MouseButton btn)
   at Silk.NET.Input.Glfw.GlfwMouse.<Subscribe>b__36_2(WindowHandle* _, MouseButton btn, InputAction action, KeyModifiers mods)
   at Silk.NET.Input.Glfw.GlfwEvents.<.ctor>b__0_2(WindowHandle* a, MouseButton b, InputAction c, KeyModifiers d)
   at Silk.NET.GLFW.Glfw.PollEvents()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()`

**Comment by Pyrdacor** [comment]
Memo to myself: Clear() and other console methods can't be used with redirection.

**Comment by Pyrdacor** [comment]
This will work in 1.4. You can also use cheats from a command shell.

**Comment by skdubg** [comment]
thanks. i close it.
