### ISSUE TITLE
Crash while opening Inventory of Party Members

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#23]
I get this crash when i try to open the inventory of the 2nd member (in my case Egil):

Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Ambermoon.Data.Legacy.ItemManager.GetItem(UInt32 index)
   at Ambermoon.UI.UIItem.Update(Boolean itemTypeChanged)
   at Ambermoon.UI.UIItem..ctor(IRenderView renderView, IItemManager itemManager, ItemSlot item)
   at Ambermoon.UI.ItemGrid.SetItem(Int32 slot, ItemSlot item)
   at Ambermoon.Game.<>c__DisplayClass92_0.<OpenPartyMember>b__0()
   at Ambermoon.Game.OpenPartyMember(Int32 slot)
   at Ambermoon.Game.OnKeyDown(Key key, KeyModifiers modifiers)
   at Ambermoon.GameWindow.Keyboard_KeyDown(IKeyboard keyboard, Key key, Int32 value)
   at Silk.NET.Input.Desktop.GlfwKeyboard.<Subscribe>b__26_1(WindowHandle* _, Keys key, Int32 code, InputAction action, KeyModifiers mods)
   at Silk.NET.Input.Desktop.GlfwEvents.<.ctor>b__0_1(WindowHandle* a, Keys b, Int32 c, InputAction d, KeyModifiers e)
   at Silk.NET.GLFW.XDFEF5638.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

**Comment by Pyrdacor** [comment]
I thin I know the cause. Can you please provide the savegame for testing? I will look at it tomorrow or on monday.

**Comment by Thallyrion** [comment]
Here is the savegame
[Save.01.zip](https://github.com/Pyrdacor/Ambermoon.net/files/5178922/Save.01.zip)

**Comment by Pyrdacor** [comment]
Interesting. Is this only true for chests that were locked at game start? Maybe your savegame will help decode the unknown bits in the chest data. :)

**Comment by Thallyrion** [comment]
Yes as far as i tested it the chest which are initially locked are locked again. The chests that are initially open are open and seem to have the correct inventory. I will further investigate this issue when i get some more time.

**Comment by Pyrdacor** [comment]
Ok your savegame could be very useful to decode much more data regarding map events. I will have a closer look at it. And the results and fixes will come with 1.0.20. ;)

**Comment by Pyrdacor** [comment]
Can you tell me which chests are the locked chests which should be open?

I fixed the other bug (release will come soon when I added load savegame stuff). The problem was that two-handed weapons set the item index for the second slot to 0 (which is a red cross). But it was no valid item index.

**Comment by Pyrdacor** [comment]
I added the load menu today. But you can only see savegames for now. Loading them is not possible yet. I will add this tomorrow hopefully and release the new version with fixes and savegame loading.

**Comment by Thallyrion** [comment]
The chests in the House of Healers should be open, also the chests in the Thieves Hideout in the desert, as well as the left chest in the Town Hall (reward chest for the thieves hideout).

**Comment by Pyrdacor** [comment]
Version 1.1.0 is out now. It should fix the crash and allow you to load savegames. :)
