### ISSUE TITLE
[Bug report] Value cannot be null. (Parameter 'destinationArray') when walking around Pelanis Palace

### ISSUE THREAD

**Issue by xenonmb** [Pyrdacor/Ambermoon.net#313]
**Describe the bug**
Game quits with the message Value cannot be null. (Parameter 'destinationArray')
From the console output it seems to be sound related?

`Value cannot be null. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at SonicArranger.TrackState.ApplyInstrumentEffects()
   at SonicArranger.TrackState.Tick(Int32 speed)
   at SonicArranger.Stream.Load(Int32 bufferIndex, Int32 numSamples, Boolean loop)
   at SonicArranger.Stream.Reset()
   at Ambermoon.Audio.OpenAL.AudioBuffers.Play(CancellationToken cancellationToken)
   at Ambermoon.Data.Legacy.Audio.SongPlayer.Start(IAudioOutput audioOutput, IAudioStream audioStream)
   at Ambermoon.Game.PlayMusic(Song song)
   at Ambermoon.EventExtensions.ExecuteEvent(Event event, Map map, Game game, EventTrigger& trigger, UInt32 x, UInt32 y, Boolean& lastEventStatus, Boolean& aborted, EventProvider& eventProvider, IConversationPartner conversationPartner, Nullable`1 characterIndex)
   at Ambermoon.MapExtensions.TriggerEvents(Map map, Game game, EventTrigger trigger, UInt32 x, UInt32 y, Savegame savegame, Boolean& hasMapEvent, Func`2 filter)
   at Ambermoon.Render.RenderMap2D.TriggerEvents(IRenderPlayer player, EventTrigger trigger, UInt32 x, UInt32 y, IMapManager mapManager, UInt32 ticks, Savegame savegame)
   at Ambermoon.Render.Player2D.Move(Int32 x, Int32 y, UInt32 ticks, TravelType travelType, Boolean& eventTriggered, Boolean displayOuchIfBlocked, Nullable`1 prevDirection, Boolean updateDirectionIfNotMoving)
   at Ambermoon.Game.<Move2D>g__Move|399_0(<>c__DisplayClass399_0& )
   at Ambermoon.Game.Move()
   at Ambermoon.Game.Update(Double deltaTime)
   at Ambermoon.GameWindow.Window_Update(Double delta)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

[Verarbeitung des Prozesses mit Code 1 (0x00000001) beendet]`

**To Reproduce**
Enter Pelanis Palace from my 1st savegame. saves here: https://we.tl/t-NAOVtMroEy
Enter the right room, with the door to the healer.
Walk around some.

**Screenshots**
https://imgur.com/5uYXsTO

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 1.6.8

**Comment by Pyrdacor** [comment]
Thanks. Will investigate this on Monday.

**Comment by Pyrdacor** [comment]
Should be fixed since 1.6.9.
