### ISSUE TITLE
[Feature request]Instructions on how to compile

### ISSUE THREAD

**Issue by TheYoctoJester** [Pyrdacor/Ambermoon.net#316]
**Is your feature request related to a problem? Please describe.**
This kinda relates to the window size problem. I agree with the idea of a dynamic size, hence I want to look into code. But I can't find a good pointer how to get started.

**Describe the solution you'd like**
A documented way of compiling a fresh clone of the repo.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Pyrdacor** [comment]
In theory you can just open the solution, select the project Ambermoon.net as the start project, compile and run. But this way you lack the builtin game data. You can download the game data from here though:  https://GitHub.com/Pyrdacor/Ambermoon. Then either put it into the Ambermoon.net sub-folder or to some other path. Then adjust the ambermoon.cfg and set "UseDataPath" to true and "DataPath" to the Amberfiles folder of the downloaded and extracted game data. If there is no ambermoon.cfg in the project folder (sub-folder Ambermoon.net) then copy the one from your game installation there.

If you want to use the version selector like in the final game (or the steps above are too complicated) you can use a publish script. Have a look here: https://github.com/Pyrdacor/Ambermoon.net/blob/master/build-win64.cmd

This script is part of the repo. It is for windows. There is also an arm64 script but this is a bit outdated. Best use the windows script and adjust it for Mac or Linux if needed.

This will create a single Ambermoon.net executable.

**Comment by TheYoctoJester** [comment]
@Pyrdacor saw the instructions! Tried to do so, but:
```
Could not find file '/Users/josef/Projects/dotnet/Ambermoon.net/Ambermoon.net/bin/Debug/net6.0/versions.dat'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Ambermoon.GameWindow.Window_Load() in /Users/josef/Projects/dotnet/Ambermoon.net/Ambermoon.net/GameWindow.cs:line 1190
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration) in /Users/josef/Projects/dotnet/Ambermoon.net/Ambermoon.net/GameWindow.cs:line 1517
   at Ambermoon.Program.Main() in /Users/josef/Projects/dotnet/Ambermoon.net/Ambermoon.net/Program.cs:line 66
```

**Comment by TheYoctoJester** [comment]
Patching the line t0
```
var builtinVersionReader = OperatingSystem.IsMacOS() && File.Exists("versions.dat") ? new BinaryReader(File.OpenRead("versions.dat")) :
                (additionalData.TryGetValue("versions", out var reader) ? reader : null);
```
got me a little further, to `Unable to find file 'AM2_CPU'.`. I've dropped the ADF files right into `Ambermoon.Net/Ambermoon.Net`.

**Comment by Pyrdacor** [comment]
Please pull again. There was an issue with ADF loading.

**Comment by Pyrdacor** [comment]
Are you on Mac? Then the patched line might be important. Feel free to commit this as well.

**Comment by Pyrdacor** [comment]
https://github.com/Pyrdacor/Ambermoon.net/blob/9d9698a25f73261f496cae9fb1a74aa326447c2b/Ambermoon.net/Configuration.cs#L194

**Comment by Pyrdacor** [comment]
If the error still happens please step through the mentioned code with the debugger and check what path is built.
