### ISSUE TITLE
Crash trying to load savegame

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#32]
After pressing the load button in the disk menu i get this error

Unhandled exception. System.IndexOutOfRangeException: Data index out of range.
   at Ambermoon.Data.Legacy.DataReader.set_Position(Int32 value)
   at Ambermoon.Data.Legacy.SavegameManager.GetSavegameNames(IGameData gameData, Int32& current)
   at Ambermoon.UI.Layout.OpenLoadMenu()
   at Ambermoon.UI.Button.ExecuteActions(UInt32 currentTicks)
   at Ambermoon.UI.Button.LeftMouseUp(Position position, Nullable`1& cursorType, UInt32 currentTicks)
   at Ambermoon.UI.ButtonGrid.MouseUp(Position position, MouseButtons mouseButtons, Nullable`1& newCursorType, UInt32 currentTicks)
   at Ambermoon.UI.Layout.LeftMouseUp(Position position, Nullable`1& newCursorType, UInt32 currentTicks)
   at Ambermoon.Game.OnMouseUp(Position position, MouseButtons buttons)
   at Ambermoon.GameWindow.Mouse_MouseUp(IMouse mouse, MouseButton button)
   at Silk.NET.Input.Desktop.GlfwMouse.<Subscribe>b__62_2(WindowHandle* _, MouseButton btn, InputAction action, KeyModifiers mods)
   at Silk.NET.Input.Desktop.GlfwEvents.<.ctor>b__0_2(WindowHandle* a, MouseButton b, InputAction c, KeyModifiers d)
   at Silk.NET.GLFW.X84D602C1.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

**Comment by Pyrdacor** [comment]
Should be fixed in 1.1.2.

There seem to be a bug in Ambermoon. The file "Saves" which contains the names of all savegames is created with 382 bytes. 2 bytes for the current savegame index and 38 bytes for each savegame slot name. The max length of a savegame is 38 chars. But each has an additional terminating null-byte. So actually each slot uses 39 bytes. Therefore the last slot can only store 29 chars instead of 38.

This was fixed in a later version I guess as I had a file with 392 bytes (39 bytes per slot). So the crash didn't occur for me. But as your file was smaller it tried to read beyond the file size and crashed. I fixed it in a way which works for both versions. Funny what is revealed by rewriting such a game. :)
