### ISSUE TITLE
[Bug report] Lizard fight crash

### ISSUE THREAD

**Issue by fluff79** [Pyrdacor/Ambermoon.net#344]
**Describe the bug**
Entered the cellar at the beginning of the game and at the well , when the lizard jumps out, the game crashes before the battle starts.

here is the error log

The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception.

   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(WriteObjectInfo objectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Ambermoon.Data.Monster.Clone()
   at Ambermoon.Data.MonsterGroup.Clone()
   at Ambermoon.Game.<>c__DisplayClass557_0.<ShowBattleWindow>b__0()
   at Ambermoon.Game.Update(Double deltaTime)
   at Ambermoon.GameWindow.Window_Update(Double delta)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Running on a windows PC, the advanced ambermoon 1.03. Downloaded it earlier this evening from github.

**Additional context**

Thank you!

**Comment by fluff79** [comment]
Reloaded the crash save and tried again without the issue reoccuring.

**Comment by Pyrdacor** [comment]
Can you start any fights?

**Comment by fluff79** [comment]
Yes I can thank you.  I haven’t been able to reproduce the error, so perhaps there isn’t really anything to do. Thanks Mark

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Pyrdacor** [comment]
Still strange that this happened. I leave this open as a reminder to have a closer look at it.

**Comment by fluff79** [comment]
Thank you.  You’re doing a wonderful thing with the project.  I never played the game when I was younger, but I loved playing DragonFlight which was a different game that Thalion made.  The graphics, music, gameplay etc amazing.  So I’m trying out Ambermoon 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Pyrdacor** [comment]
This never happened again I guess. I will close this now. If it occurs again, someone will most likely create a new issue and I can investigate further then if needed.
