### ISSUE TITLE
[Bug report] Crash when accidentally entering \ in the time to wait dialog

### ISSUE THREAD

**Issue by orgi** [Pyrdacor/Ambermoon.net#352]
**Describe the bug**
Crash when accidentally entering \ instead of a time to wait when wanting to wait for a certain amount of time

**To Reproduce**
1. Press to the hourglass icon when in a dungeon (maybe works outside, too?)
2. Click into the 'How many hours to wait' box.
3. Press the \ button on your keyboard
4. Game will crash. Following error will be shown:
DATA  UNSUPPORTED TEXT CHARACTER ' '

Stack Trace:
```
[Data] Unsupported text character '\'.
   at Ambermoon.Data.Legacy.TextProcessor.CharToGlyph(Char ch, Boolean rune, Nullable`1 fallbackChar)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Ambermoon.Data.Legacy.TextProcessor.FinalizeText(IEnumerable`1 glyphs)
   at Ambermoon.UI.TextInput.UpdateText()
   at Ambermoon.UI.TextInput.KeyChar(Char ch)
   at Ambermoon.UI.Popup.KeyChar(Char ch)
   at Ambermoon.UI.Layout.KeyChar(Char ch)
   at Ambermoon.Game.OnKeyChar(Char keyChar)
   at Ambermoon.GameWindow.Keyboard_KeyChar(IKeyboard keyboard, Char keyChar)
   at Silk.NET.Input.Glfw.GlfwKeyboard.<Subscribe>b__31_0(WindowHandle* _, UInt32 c)
   at Silk.NET.Input.Glfw.GlfwEvents.<.ctor>b__0_0(WindowHandle* a, UInt32 b)
   at Silk.NET.GLFW.Glfw.PollEvents()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Silk.NET.Windowing.IView.DoEvents()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
Press return to exit
```

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 1.7.3

**Comment by Pyrdacor** [comment]
Fixed in 1.8.4
