### ISSUE TITLE
game exits when giving a single horseshoe to Tolimar in Spannenberg

### ISSUE THREAD

**Issue by sh-dave** [Pyrdacor/Ambermoon.net#378]
**To Reproduce**
- collect horseshoes for Tolimar
- split the stack of 4; in my case I split them into 4x1
- talk to Tolimar and give him a horseshoe
- Tolimar will be happy, acting like you gave him all 4
- the game is not so happy and will go💥 

**Screenshots**
```
[Application] Tried to remove more items than existed.
   at Ambermoon.Data.ItemSlot.Remove(Int32 amount)
   at Ambermoon.Game.<>c__DisplayClass575_5.<ShowConversation>b__44()
   at Ambermoon.Render.ItemAnimation.<>c__DisplayClass9_0.<Play>g__Start|0()
   at Ambermoon.Game.Update(Double deltaTime)
   at Ambermoon.GameWindow.Window_Update(Double delta)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
   at Silk.NET.Windowing.Glfw.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
Press return to exit
```

**Desktop (please complete the following information):**
 - Windows 10
- Ambermoon Original 1.19 Deutsch

**Comment by sh-dave** [comment]
In addition: I was offered to load a crash backup save, but there was only a single horseshoe in Egil's inventory now.

**Comment by Pyrdacor** [comment]
Interesting. I will have a look at it soon.

**Comment by Pyrdacor** [comment]
Sorry for 1 year until I got to it... I tested it right now and for me it works. Most likely I fixed this already for something else. The error message rings a bell of some recent issue I fixed. I will release a new version shortly. It should be working then.
