### ISSUE TITLE
Crash when clicking on load savegame symbol - 1.1.14

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#49]
I get  the following crash when i click on the load savegame symbol

Unhandled exception. Ambermoon.AmbermoonException: [Data] Unsupported text character '▄'.
   at Ambermoon.Data.Legacy.TextProcessor.CharToGlyph(Char ch, Boolean rune)
   at Ambermoon.Data.Legacy.TextProcessor.<>c.<CreateText>b__2_0(Char ch)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Ambermoon.Data.Legacy.TextProcessor.FinalizeText(IEnumerable`1 glyphs)
   at Ambermoon.Data.Legacy.TextProcessor.CreateText(String text)
   at Ambermoon.UI.Popup.AddText(Position position, String text, TextColor textColor, Boolean shadow, Byte displayLayer)
   at Ambermoon.UI.ListBox..ctor(IRenderView renderView, Game game, Popup popup, List`1 items, Rect area, Position itemBasePosition, Int32 itemHeight, Int32 hoverBoxWidth, Position relativeHoverBoxOffset, Boolean withIndex, Int32 maxItems)
   at Ambermoon.UI.ListBox.CreateSavegameListbox(IRenderView renderView, Game game, Popup popup, List`1 items)
   at Ambermoon.UI.Popup.AddSavegameListBox(List`1 items)
   at Ambermoon.UI.Layout.OpenLoadMenu()
   at Ambermoon.UI.Button.ExecuteActions(UInt32 currentTicks)
   at Ambermoon.UI.Button.LeftMouseUp(Position position, Nullable`1& cursorType, UInt32 currentTicks)
   at Ambermoon.UI.ButtonGrid.MouseUp(Position position, MouseButtons mouseButtons, Nullable`1& newCursorType, UInt32 currentTicks)
   at Ambermoon.UI.Layout.LeftMouseUp(Position position, Nullable`1& newCursorType, UInt32 currentTicks)
   at Ambermoon.Game.OnMouseUp(Position cursorPosition, MouseButtons buttons)
   at Ambermoon.GameWindow.Mouse_MouseUp(IMouse mouse, MouseButton button)
   at Silk.NET.Input.Desktop.GlfwMouse.<Subscribe>b__62_2(WindowHandle* _, MouseButton btn, InputAction action, KeyModifiers mods)
   at Silk.NET.Input.Desktop.GlfwEvents.<.ctor>b__0_2(WindowHandle* a, MouseButton b, InputAction c, KeyModifiers d)
   at Silk.NET.GLFW.X8A925E35.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

My guess is this happens because of unsupported "space character" in savegame name

**Comment by Pyrdacor** [comment]
Can you provide the savegame name or file please?

**Comment by Pyrdacor** [comment]
If you provide the files I also need the file "Saves".

**Comment by Thallyrion** [comment]
I just noticed that one Savegame also contains an "ü" this could be a cause too.
[savegames with space.zip](https://github.com/Pyrdacor/Ambermoon.net/files/5348776/savegames.with.space.zip)

**Comment by Pyrdacor** [comment]
I don't think it's a space character as they are handled. Maybe an apostrophe? They weren't handled correctly.

I fixed apostrophe handling and invalid chars in savegame names should now be replaced with a '?'. Check out v1.1.15 which is coming in a few seconds.

**Comment by Thallyrion** [comment]
Okay tested this with 1.1.15 and my last guess was correct. The German ü,ä,ö aren't supported. Possibly other characters too. So this needs to be corrected.

**Comment by Pyrdacor** [comment]
Oh I nearly forgot about that issue. Will check on that soon.

**Comment by Pyrdacor** [comment]
German umlauts should now work in 1.1.17. I also fixed crashes when clicking on empty savegames in the load menu.
