### ISSUE TITLE
[Announcement] Linux version

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon.net#61]
Version 0.1.1. beta is now also available for 64bit Linux (Ubuntu etc). I didn't test it though. Maybe someone else can test it and give me feedback.

**Comment by kermitfrog** [comment]
Yay! I have not seen the Ambermoon 3D parts run this fluent since I had a real Amiga :)
It basically works, but there are bugs (of course):

- Known spells are shifted by +1. e.g. Nelvin has Winddevil, but in Ambermoon.net it's Windhowler instead. Also, when I cast it in combat, Iceball is cast instead.
- Several UI issues (as expected in a beta)
- Game hangs after first attack on monster (not after attacks by monsters or spells)
- Always crashes on loading one (and just that one) of my saved games. Output is:
`Unhandled exception. Ambermoon.AmbermoonException: [Data] Character with more than 1 sub objects.
   at Ambermoon.Render.RenderMap3D.AddMapCharacter(ISurface3DFactory surfaceFactory, IRenderLayer layer, UInt32 characterIndex, CharacterReference characterReference)
   at Ambermoon.Render.RenderMap3D.AddCharacters()
   at Ambermoon.Render.RenderMap3D.SetMap(Map map, UInt32 playerX, UInt32 playerY, CharacterDirection playerDirection)
   at Ambermoon.Game.Start3D(Map map, UInt32 playerX, UInt32 playerY, CharacterDirection direction, Boolean initial)
   at Ambermoon.Game.Start(Savegame savegame)
   at Ambermoon.Game.LoadGame(Int32 slot)
   at Ambermoon.UI.Layout.<OpenLoadMenu>b__93_1(Int32 slot, String name)
   at Ambermoon.UI.ListBox.Click(Position position)
   at Ambermoon.UI.Popup.Click(Position position, MouseButtons mouseButtons, Boolean& ignoreNextMouseUp)
   at Ambermoon.UI.Layout.Click(Position position, MouseButtons buttons, CursorType& cursorType, UInt32 currentTicks, Boolean pickingNewLeader)
   at Ambermoon.Game.OnMouseDown(Position position, MouseButtons buttons)
   at Silk.NET.Input.Desktop.GlfwMouse.HandleMouseDown(IMouse mouse, MouseButton button)
   at Silk.NET.GLFW.X91CAB73E.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
Fatal error. Internal CLR error. (0x80131506)
   at Silk.NET.GLFW.X91CAB73E.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions+<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(System.Action)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(Silk.NET.Windowing.Common.IView)
   at Ambermoon.GameWindow.Run(Ambermoon.Configuration)
   at Ambermoon.Program.Main()`

**Comment by Pyrdacor** [comment]
Thanks for testing.

- I noticed the known spells shift as well but didn't have the time to fix it. Will do so soon.
- Iceball is the fallback spell at the moment. Only a few spells are implemented atm. These are: Firebeam, Fireball, Firestorm, Firepillar, Iceball, Dissolve Victim and all curse spells. These should work. The rest is replaced by Iceball instead. So this is no real bug.
- About the UI issues. Would be nice if you could add a new issue here on github called "UI issues" where we can add and track those issues so I can fix them one by one and we won't forget about them. :)
- I will check the hang for myself.
- The crash is very interesting. 3D map objects can have up to 8 subobjects. Characters like NPCs or monsters are map objects as well but I though they can only have one subobject. The error messages shows the opposite. Can you share the savegame and tell me on which map you are in the original?

**Comment by Pyrdacor** [comment]
@kermitfrog FYI the tools are now also available on Linux: https://github.com/Pyrdacor/Ambermoon/releases/download/v1.0.3/AmbermoonTools-Linux.tar.gz

But I haven't tested them on Linux yet. You should start them from a shell without parameters or with "--help" to see what arguments are possible. The argument documentation might show Windows-like paths like "C:\my\path" but you should use Linux-style paths like "./my/path" instead. Let me know if they work.

**Comment by Pyrdacor** [comment]
[Monster_char_data.amb.tar.gz](https://github.com/Pyrdacor/Ambermoon.net/files/5672064/Monster_char_data.amb.tar.gz)

Here are the decoded and extracted monster character data files (I think the german ones).

**Comment by a1exh** [comment]
I tried it on my linux here (Centos 7.8) and it didn't run. I think our workstations must not have OpenGL installed? I don't have SUDO access so that is it for me testing... sorry.

```
cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

./Ambermoon.net
Couldn't find a suitable windowing platform. 
GLFW: Copy a GLFW 3.3 binary into the same directory as Ambermoon.net.dll

   at Silk.NET.Windowing.Window.Init()
   at Silk.NET.Windowing.Window.Create(WindowOptions options)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
```

**Comment by a1exh** [comment]
Oh and GLFW 3.3 isn't supported on Centos 7 either :(

**Comment by Pyrdacor** [comment]
I use Silk.NET as a OpenGL and Windowing backend and contribute to this project as well. There is a new version which supports SDL instead of GLFW. I will update it soon so it might run on CentOS as well hopefully.

**Comment by kermitfrog** [comment]
Ok... I think the tools work. That is.. they all do something and if I use AmbermoonPack it to pack Monster_char_data.amb you posted and compare that with the one in my game dir, it looks similiar in a hex editor. There are differences, but thats likely due to different versions. (the created file has a md5 of 63edd31970123b149be80ebf3828e6d6 ).

**Comment by Pyrdacor** [comment]
Great to hear. I also tested the game and tools on Ubuntu 20.04 and they worked for me without problems.

The differences can also be caused by the compression algorithm. I wrote my own LOB compression which isn't 100% equal to the original one but will produce a valid output as well and the compression rate is very similar, sometimes even a bit better.

**Comment by a1exh** [comment]
There can sometimes be redundant data at the end of sub-blocks, spaces before text and other things which the Ambermoon.net tools remove resulting in slightly different files and block lengths before compression.

**Comment by kermitfrog** [comment]
> The crash is very interesting. [..] Can you share the savegame and tell me on which map you are in the original?

Almost forgot about that.. It's in "Dorinas Höhle Unten". Here it is:
[Save.10.tar.gz](https://github.com/Pyrdacor/Ambermoon.net/files/5675503/Save.10.tar.gz)

On a sidenote, I can now confirm that the MonsterValueChanger is definitely working on linux, as I used it to confirm a suspicion (see other thread).

**Comment by Pyrdacor** [comment]
@kermitfrog FYI: The crash should be gone with 0.1.8beta.
